opera target view
eclipse-symphony/symphony pull request #246
Opened 2024-05-02 20:53 UTC by Haishi2016

This should be safe to merge as it affects only the opera portal.

2024-05-11 00:21 UTC, msftcoderdjw commented
Hi @Haishi2016 , eclipsefdn/eca checke failed in this PR. Can you please take a look?

2024-05-11 01:07 UTC, msftcoderdjw requested changes

2024-05-11 01:07 UTC, msftcoderdjw commented on README.md
> +### ⚠️⚠️⚠️ This branch hosts experimental features. The Symphony community does not guarantee long-term support for these features. Their incorporation into the main branch is not assured, and they m
Not include this in main.

2024-05-11 01:07 UTC, msftcoderdjw commented on api/pkg/apis/v1alpha1/managers/stage/stage-manager.go
> +						Proxy:                cam.Stages[nextStage].Proxy,
These are the proxy processor changes, please remove them.

2024-05-13 17:04 UTC, Haishi2016 commented
> Hi @Haishi2016 , eclipsefdn/eca checke failed in this PR. Can you please take a look?

This is because there's a commit from action@github.com ....

2024-05-14 12:13 UTC, msftcoderdjw commented on api/pkg/apis/v1alpha1/managers/stage/stage-manager.go
> +		case float64:
Just curious in which case, we will get float64 status?

2024-05-14 12:17 UTC, msftcoderdjw commented on docs/samples/opera/app/types.d.ts
> +export interface TargetState {
I saw in this file, there's still some object like SolutionState which doesn't align new object model. Do we need to fix them?

2024-05-16 17:03 UTC, closed without merging