Handle type conversion error in state providers
eclipse-symphony/symphony pull request #258
Opened 2024-05-14 05:39 UTC by RemindD

Fix https://github.com/eclipse-symphony/symphony/issues/257

2024-05-14 06:11 UTC, msftcoderdjw reviewed
The title seems to be stage providers.

2024-05-14 06:24 UTC, msftcoderdjw requested changes
Please help to go through the whole codebase. I found we have similar issues in reference manager. Please try to fix as much as possible.

2024-05-15 12:07 UTC, msftcoderdjw approved these changes

2024-05-15 18:43 UTC, Haishi2016 approved these changes

2024-05-16 03:43 UTC, merged