Turn off validation for standalone mode
eclipse-symphony/symphony pull request #446
Opened 2024-08-30 07:24 UTC by RemindD

There are some issues for object validation in standalone mode. Details can be found in https://github.com/eclipse-symphony/symphony/issues/445.

Turn off the validation temporarily to unblock object creation.

2024-09-03 19:11 UTC, Haishi2016 reviewed
I propose looking at how a shared pubsub provider can be initialized for the entire API. Maybe we can use similar mechanisms to initialize a shared memory state provider and use keyed lock for concurrency control

2024-09-05 23:37 UTC, Haishi2016 approved these changes

2024-09-06 19:51 UTC, Haishi2016 reviewed
We need more discussions on this. Please hold off merging this PR.

2024-09-06 19:51 UTC, Haishi2016 requested changes
We need to discuss more on this.

2024-09-09 16:56 UTC, Haishi2016 approved these changes

2024-09-10 01:39 UTC, msftcoderdjw approved these changes

2024-09-10 01:41 UTC, merged