added oci username and password auth for helm provider
eclipse-symphony/symphony pull request #490
Opened 2024-09-25 02:50 UTC by iwangjintian

also added http request with sastoken support

2024-09-25 20:52 UTC, Haishi2016 approved these changes

2024-09-26 00:19 UTC, msftcoderdjw reviewed
Please add docs to explain this new feature in helm-target provider.

2024-09-29 01:02 UTC, msftcoderdjw requested changes

2024-09-29 07:32 UTC, msftcoderdjw approved these changes

2024-09-29 07:32 UTC, merged