init piccolo
eclipse-symphony/symphony pull request #502
Opened 2024-10-02 03:06 UTC by youngtaekiim

A new version of PR#488
previous : https://github.com/eclipse-symphony/symphony/pull/488

2024-10-03 19:27 UTC, Haishi2016 requested changes

2024-10-03 19:27 UTC, Haishi2016 commented on api/pkg/apis/v1alpha1/providers/target/piccolo/piccolo.go
> +		req, err := http.NewRequest("GET", i.Config.Url+workloadType+"/"+name, nil)
The Get() method and Apply() method should be consistent. For example, the Get() method gets by the path "workload.type/workload.name", while the Apply() method posts to path component.Name, which isn't necessary the same with workload.name. If workload.name and component.name are the same, probably we should exclude workload.name in properties and use component.Name in Get()

2024-10-03 19:38 UTC, Haishi2016 commented on api/pkg/apis/v1alpha1/providers/target/piccolo/piccolo.go
> +		req, err := http.NewRequest("GET", i.Config.Url+workloadType+"/"+name, nil)
Also, the Apply() method doesn't use workload.type. Maybe workload.type should be included in the request properties?

2024-10-03 20:14 UTC, Haishi2016 requested changes

2024-10-03 20:14 UTC, Haishi2016 commented on api/pkg/apis/v1alpha1/providers/target/piccolo/piccolo.go
> +	}
Extract url from properties here. Throw COAError if url is not found in properties.

2024-10-04 00:41 UTC, closed without merging

2024-10-04 00:59 UTC, youngtaekiim commented
I am sorry that I accidentally changed the repository and made a wrong commit fix (amend), which caused the existing PR to be closed.
I post response to existing your code reviews in https://github.com/eclipse-symphony/symphony/pull/503.