Changed Links and added buttons
eclipse-symphony/symphony pull request #524
Opened 2024-10-18 19:05 UTC by hariarun18

2024-10-18 21:02 UTC, Haishi2016 requested changes
Please also accept license agreement before this PR can be accepted.

2024-10-18 21:02 UTC, Haishi2016 commented on landing/config/_default/params.toml
> +# Type of pages to be rendered with a blog vie
typo - vie(w)

2024-10-20 19:21 UTC, hariarun18 commented on landing/config/_default/params.toml
> +# Type of pages to be rendered with a blog vie
Spelling issue fixed in 10/20 commit

2024-10-20 19:29 UTC, hariarun18 commented
Have completed the ECA agreements - not reflecting here, if this prevents this from moving forward I can follow up with Eclipse team. OCX 2024 Blocker.

2024-10-21 21:09 UTC, Haishi2016 approved these changes

2024-10-21 21:10 UTC, merged